Sprint 9
Pussmal/ImageFeed pull request #2
Opened 2023-01-09 17:31 UTC by Pussmal

Добрый день!
Направляю на проверку sprint 9

2023-01-10 15:54 UTC, mmbabaev requested changes

2023-01-10 15:54 UTC, mmbabaev commented on ImageFeed/Profile/ProfileScreenView.swift
> +final class ProfileScreenView: UIView {
отлично, что вынесли в отдельную UIView

2023-01-10 15:54 UTC, mmbabaev commented on ImageFeed/Profile/ProfileScreenView.swift
> +            exitButton.heightAnchor.constraint(equalToConstant: 44),
хорошо, что поставили констрейнты размеров для кнопки

2023-01-10 15:54 UTC, mmbabaev commented on ImageFeed/Profile/ProfileViewController.swift
> +    private func viewSetting() {
нет действия в названии функции, `setupView`?

2023-01-10 15:54 UTC, mmbabaev commented on ImageFeed/Profile/ProfileViewController.swift
> +    private var profileScreen = ProfileScreenView()
лучше показать, что это view: `profileScreenView`

2023-01-11 08:21 UTC, Pussmal commented
Добрый день!
Спасибо за замечания, все поправил.

2023-01-11 18:11 UTC, mmbabaev approved these changes

2023-01-11 18:11 UTC, mmbabaev commented on ImageFeed/ImageList/ImagesListViewController.swift
>      private let photosName = Array(0..<20).map { "\($0)" }
тут еще лучше `photoNames` (знаю, что по учебнику)

2023-01-11 18:11 UTC, mmbabaev commented on ImageFeed/ImageList/SharingPresenter/SharingPresenter.swift
> +            fatalError()
Можно использовать `assertionFailure`, вместо этого. Так для внутренних сборок разработчик/тестировщик увидят краш, а у пользователя просто ничего не произойдет (хотя есть мнение, что это хуже краша)

2023-01-19 06:04 UTC, merged